package springboot.template.controller;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import springboot.template.application.SampleAppService;
import springboot.template.dto.InputDTO;
import springboot.template.dto.OutputDTO;
import springboot.template.exception.RegisterException;
import springboot.template.exception.ValidateRegisterException;

/**
 * Class auto-generated by archetype-spring project
 * Repository: http://californio.keynet.com.br:8089/java/archetype/archetype-spring
 */
@RestController
public class SampleController {

    static final String HOME_MESSAGE = "Hello World";
    // Controllers must have only application; never model/service
    private final SampleAppService sampleApp;

    @Autowired
    public SampleController(SampleAppService sampleApp) {
        this.sampleApp = sampleApp;
    }

    @GetMapping(produces = MediaType.TEXT_PLAIN_VALUE)
    public ResponseEntity<String> index() {
        return ResponseEntity.status(HttpStatus.OK).body(HOME_MESSAGE);
    }

    @PostMapping(consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
    public OutputDTO postSample(@RequestBody InputDTO inputDTO) throws RegisterException, ValidateRegisterException {
        return sampleApp.process(inputDTO);
    }

}